service:
  user:
    url: http://localhost:8081/
    endpoint: users
  cryptocurrency:
    url: http://localhost:8082/
    endpoint: cryptocurrency

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    instances:
      userService:
        baseConfig: default
        failureRateThreshold: 20
      cryptocurrencyService:
        baseConfig: default
